FROM node:18 as development

EXPOSE 8080

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install app dependencies
RUN npm install --legacy-peer-deps

# Bundle app source
COPY . .

RUN npm run build

ENV NODE_ENV development

CMD [ "node", "dist/src/main.js" ]