services:
  postgresql:
    container_name: postgresql
    image: postgres
    env_file:
      - env/.env.development
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgresql-data:/var/lib/postgresql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - env/.env.development
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    restart: unless-stopped
    depends_on:
      - postgresql

  app:
    depends_on:
      - postgresql
    container_name: sonat-bi-reward-system
    build:
      context: .
      dockerfile: Dockerfile-development
    env_file:
      - env/.env.development
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  postgresql-data: